server:
  port: 8081

spring:
  application:
    name: asm-router-service
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myusername
    password: mysecurepassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

asm:
  hashing:
    virtual-nodes: 100